apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: taint-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: taint-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: taint-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest