apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-toleration
  labels:
    purpose: toleration-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: toleration-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: toleration-demo
        project: roboshop
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-51-145.ec2.internal
      containers:
      - name: nginx
        image: nginx:latest
      tolerations:
      - key: "project"
        operator: "Equal"
        value: "roboshop"
        effect: "NoSchedule"