apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    app: store
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In 
                values: 
                - store
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - name: redis
        image: redis:3.2-alpine